# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [1]:
import pandas as pd

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [45]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [5]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [6]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [7]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

[{'_id': {'$oid': '52b213b38594d8a2be17c780'},
  'approvalfy': 1999,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-12T00:00:00Z',
  'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  'closingdate': '2018-07-07T00:00:00Z',
  'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
  'countrycode': 'ET',
  'countryname': 'Federal Democratic Republic of Ethiopia',
  'countryshortname': 'Ethiopia',
  'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 0,
  'ibrdcommamt': 0,
  'id': 'P129828',
  'idacommamt': 130000000,
  'impagency': 'MINISTRY OF EDUCATION',
  'lendinginstr': 'Investment Project Financing',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 550000000,
  'majorsector_percent': [{'Name': 'Education', 'Percent': 46},
   {'Name': 'Education', 'Percent': 26},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 16},
   {'Name': 'Education', 'Percent': 12}],
  'mjsector_namecode': [{'name': 'Education', 'code': 'EX'},
   {'name': 'Education', 'code': 'EX'},
   {'name': 'Public Administration, Law, and Justice', 'code': 'BX'},
   {'name': 'Education', 'code': 'EX'}],
  'mjtheme': ['Human development'],
  'mjtheme_namecode': [{'name': 'Human development', 'code': '8'},
   {'name': '', 'code': '11'}],
  'mjthemecode': '8,11',
  'prodline': 'PE',
  'prodlinetext': 'IBRD/IDA',
  'productlinetype': 'L',
  'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  'project_name': 'Ethiopia General Education Quality Improvement Project II',
  'projectdocs': [{'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocType': 'PID',
    'EntityID': '090224b081e545fb_1_0',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    'DocDate': '28-AUG-2013'},
   {'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    'DocType': 'IP',
    'EntityID': '000442464_20130920111729',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    'DocDate': '01-JUL-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocType': 'PID',
    'EntityID': '090224b0817b19e2_1_0',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    'DocDate': '22-NOV-2012'}],
  'projectfinancialtype': 'IDA',
  'projectstatusdisplay': 'Active',
  'regionname': 'Africa',
  'sector': [{'Name': 'Primary education'},
   {'Name': 'Secondary education'},
   {'Name': 'Public administration- Other social services'},
   {'Name': 'Tertiary education'}],
  'sector1': {'Name': 'Primary education', 'Percent': 46},
  'sector2': {'Name': 'Secondary education', 'Percent': 26},
  'sector3': {'Name': 'Public administration- Other social services',
   'Percent': 16},
  'sector4': {'Name': 'Tertiary education', 'Percent': 12},
  'sector_namecode': [{'name': 'Primary education', 'code': 'EP'},
   {'name': 'Secondary education', 'code': 'ES'},
   {'name': 'Public administration- Other social services', 'code': 'BS'},
   {'name': 'Tertiary education', 'code': 'ET'}],
  'sectorcode': 'ET,BS,ES,EP',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Education for all', 'Percent': 100},
  'theme_namecode': [{'name': 'Education for all', 'code': '65'}],
  'themecode': '65',
  'totalamt': 130000000,
  'totalcommamt': 130000000,
  'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {'_id': {'$oid': '52b213b38594d8a2be17c781'},
  'approvalfy': 2015,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-04T00:00:00Z',
  'borrower': 'GOVERNMENT OF TUNISIA',
  'country_namecode': 'Republic of Tunisia!$!TN',
  'countrycode': 'TN',
  'countryname': 'Republic of Tunisia',
  'countryshortname': 'Tunisia',
  'docty': 'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 4700000,
  'ibrdcommamt': 0,
  'id': 'P144674',
  'idacommamt': 0,
  'impagency': 'MINISTRY OF FINANCE',
  'lendinginstr': 'Specific Investment Loan',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 5700000,
  'majorsector_percent': [{'Name': 'Public Administration, Law, and Justice',
    'Percent': 70},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 30}],
  'mjsector_namecode': [{'name': 'Public Administration, Law, and Justice',
    'code': 'BX'},
   {'name': 'Public Administration, Law, and Justice', 'code': 'BX'}],
  'mjtheme': ['Economic management', 'Social protection and risk management'],
  'mjtheme_namecode': [{'name': 'Economic management', 'code': '1'},
   {'name': 'Social protection and risk management', 'code': '6'}],
  'mjthemecode': '1,6',
  'prodline': 'RE',
  'prodlinetext': 'Recipient Executed Activities',
  'productlinetype': 'L',
  'project_name': 'TN: DTF Social Protection Reforms Support',
  'projectdocs': [{'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000333037_20131024115616',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000356161_20131024151611',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000442464_20131031112136',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000333037_20131031105716',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000356161_20130305113209',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    'DocDate': '16-JAN-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000356161_20130305113716',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    'DocDate': '16-JAN-2013'}],
  'projectfinancialtype': 'OTHER',
  'projectstatusdisplay': 'Active',
  'regionname': 'Middle East and North Africa',
  'sector': [{'Name': 'Public administration- Other social services'},
   {'Name': 'General public administration sector'}],
  'sector1': {'Name': 'Public administration- Other social services',
   'Percent': 70},
  'sector2': {'Name': 'General public administration sector', 'Percent': 30},
  'sector_namecode': [{'name': 'Public administration- Other social services',
    'code': 'BS'},
   {'name': 'General public administration sector', 'code': 'BZ'}],
  'sectorcode': 'BZ,BS',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Other economic management', 'Percent': 30},
  'theme_namecode': [{'name': 'Other economic management', 'code': '24'},
   {'name': 'Social safety nets', 'code': '54'}],
  'themecode': '54,24',
  'totalamt': 0,
  'totalcommamt': 4700000,
  'url': 'http://www.worldbank.org/projects/P144674?lang=en'}]

In [8]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [47]:
#QUESTION ONE

json_data = pd.read_json('data/world_bank_projects.json')

In [15]:
occurrences = json_data.groupby('countryname').countryname.count().reset_index(name="count")
occurrences.sort_values('count', ascending=False)
#Top ten countries are China, Indonesia, Vietnam, India, Yemen, Bangladesh, Nepal, Morocco, Mozambique, Burkina Faso

                                  countryname  count
39                 People's Republic of China     19
64                      Republic of Indonesia     19
107             Socialist Republic of Vietnam     17
63                          Republic of India     16
97                          Republic of Yemen     13
38            People's Republic of Bangladesh     12
34                                      Nepal     12
25                         Kingdom of Morocco     12
76                     Republic of Mozambique     11
0                                      Africa     11
5                                Burkina Faso      9
15              Federative Republic of Brazil      9
19               Islamic Republic of Pakistan      9
89                     Republic of Tajikistan      8
115               United Republic of Tanzania      8
42                        Republic of Armenia      8
14                Federal Republic of Nigeria      7
29           Lao People's Democratic Republic      7
17                Hashemite Kingdom of Jordan      7
28                            Kyrgyz Republic      7
116                        West Bank and Gaza      6
66                          Republic of Kenya      6
78                      Republic of Nicaragua      6
20               Islamic State of Afghanistan      6
81                           Republic of Peru      6
9            Democratic Republic of the Congo      6
110  The Independent State of Papua New Guine      5
79                          Republic of Niger      5
62                       Republic of Honduras      5
61                          Republic of Haiti      5
..                                        ...    ...
57                        Republic of Ecuador      2
7    Democratic Republic of Sao Tome and Prin      2
23                        Kingdom of Cambodia      2
8          Democratic Republic of Timor-Leste      2
18             Islamic Republic of Mauritania      2
40             Plurinational State of Bolivia      2
47                       Republic of Cameroon      2
12                    Europe and Central Asia      1
111                                    Tuvalu      1
11                      East Asia and Pacific      1
10   Democratic Socialist Republic of Sri Lan      1
6                    Central African Republic      1
4                      Bosnia and Herzegovina      1
104                                   Romania      1
80                         Republic of Panama      1
26                        Kingdom of Thailand      1
27                           Kingdom of Tonga      1
77                        Republic of Namibia      1
37                People's Republic of Angola      1
44                        Republic of Belarus      1
48                     Republic of Cape Verde      1
49                           Republic of Chad      1
50                          Republic of Chile      1
52                          Republic of Congo      1
53                     Republic of Costa Rica      1
1                         Antigua and Barbuda      1
67                       Republic of Kiribati      1
85                         Republic of Serbia      1
82                         Republic of Poland      1
99                       Republic of Zimbabwe      1

[118 rows x 2 columns]

In [ ]:
#NEXT STEPS: Move lines 51, 52, 53 into question 2 section. 

#Groupby function in order to determine 10 most common codes.

In [34]:
#Question TWO

json_df = pd.read_json('data/world_bank_projects.json')

In [51]:
json_test = json.load((open('data/world_bank_projects.json')))

In [52]:
type(json_test)

list

In [54]:
norm_json = json_normalize(json_test, 'mjtheme_namecode')

In [65]:
counts = norm_json.groupby(['code']).count()
list = counts.sort_values(['code'], ascending=False)

In [87]:
type(norm_json['name'])

pandas.core.series.Series

In [83]:
norm_json.head(500)
#norm_json[norm_json['code'] =='9']

    code                                          name
0      8                             Human development
1     11
2      1                           Economic management
3      6         Social protection and risk management
4      5                         Trade and integration
5      2                      Public sector governance
6     11  Environment and natural resources management
7      6         Social protection and risk management
8      7                   Social dev/gender/inclusion
9      7                   Social dev/gender/inclusion
10     5                         Trade and integration
11     4      Financial and private sector development
12     6         Social protection and risk management
13     6
14     2                      Public sector governance
15     4      Financial and private sector development
16    11  Environment and natural resources management
17     8
18    10                             Rural development
19     7
20     2                      Public sector governance
21     2                      Public sector governance
22     2                      Public sector governance
23    10                             Rural development
24     2
25    10                             Rural development
26     6         Social protection and risk management
27     6         Social protection and risk management
28    11  Environment and natural resources management
29     4
..   ...                                           ...
470   11  Environment and natural resources management
471    9
472   11  Environment and natural resources management
473   11  Environment and natural resources management
474   11  Environment and natural resources management
475    2                      Public sector governance
476   11  Environment and natural resources management
477   11  Environment and natural resources management
478   10                             Rural development
479   10                             Rural development
480    5                         Trade and integration
481    4      Financial and private sector development
482    4      Financial and private sector development
483    5                         Trade and integration
484    8                             Human development
485    8                             Human development
486    2
487    5                         Trade and integration
488    4      Financial and private sector development
489    2                      Public sector governance
490    8                             Human development
491    2                      Public sector governance
492    7                   Social dev/gender/inclusion
493    3
494    4      Financial and private sector development
495    6         Social protection and risk management
496    2                      Public sector governance
497    1                           Economic management
498    5                         Trade and integration
499    6         Social protection and risk management

[500 rows x 2 columns]

In [66]:
print(list)
#The top 10 project themes are:
#1. Environment/Natural Resource Mgmt
#2. Rural Development
#3. Human Development
#4. Public Sector Governance
#5. Social Protection and Risk Mgmt
#6. Financial/Private Sector Development
#7. Social dev/gender/inclusion
#8. Trade and integration
#9. Urban Development
#10. Economic Management.
#Counts below:

      name
code
11     250
10     216
8      210
2      199
6      168
4      146
7      130
5       77
9       50
1       38
3       15

In [103]:
#QUESTION THREE

In [82]:
#Make a dict for thse values to map
dict = {'1': 'Economic Management', '2': 'Public Sector Governance', '3': 'Rule of Law', '4': 'Financial and Private Sector Development', '5':'Trade and Integration', '6':'Social Protection and Risk Management', '7':'Social dev/gender/inclusion', '8':'Human Development', '9': 'Urban Development', '10':'Rural Development', '11':'Environment/Natural Resource Management'}

In [101]:
norm_json2 = norm_json
norm_json2['name'] = pd.Series()
idx = 0 
while idx < len(norm_json2):
    
    a = str(norm_json2.iloc[(idx), 0])
    #print(a)
    norm_json2.iloc[(idx), 1] = dict[a]
    idx += 1

In [102]:
norm_json2

     code                                      name
0       8                         Human Development
1      11   Environment/Natural Resource Management
2       1                       Economic Management
3       6     Social Protection and Risk Management
4       5                     Trade and Integration
5       2                  Public Sector Governance
6      11   Environment/Natural Resource Management
7       6     Social Protection and Risk Management
8       7               Social dev/gender/inclusion
9       7               Social dev/gender/inclusion
10      5                     Trade and Integration
11      4  Financial and Private Sector Development
12      6     Social Protection and Risk Management
13      6     Social Protection and Risk Management
14      2                  Public Sector Governance
15      4  Financial and Private Sector Development
16     11   Environment/Natural Resource Management
17      8                         Human Development
18     10                         Rural Development
19      7               Social dev/gender/inclusion
20      2                  Public Sector Governance
21      2                  Public Sector Governance
22      2                  Public Sector Governance
23     10                         Rural Development
24      2                  Public Sector Governance
25     10                         Rural Development
26      6     Social Protection and Risk Management
27      6     Social Protection and Risk Management
28     11   Environment/Natural Resource Management
29      4  Financial and Private Sector Development
...   ...                                       ...
1469    8                         Human Development
1470    9                         Urban Development
1471    6     Social Protection and Risk Management
1472    6     Social Protection and Risk Management
1473    9                         Urban Development
1474    2                  Public Sector Governance
1475    2                  Public Sector Governance
1476   10                         Rural Development
1477   11   Environment/Natural Resource Management
1478    8                         Human Development
1479    7               Social dev/gender/inclusion
1480   11   Environment/Natural Resource Management
1481    5                     Trade and Integration
1482    6     Social Protection and Risk Management
1483    8                         Human Development
1484    4  Financial and Private Sector Development
1485    7               Social dev/gender/inclusion
1486    8                         Human Development
1487    5                     Trade and Integration
1488    2                  Public Sector Governance
1489    8                         Human Development
1490   10                         Rural Development
1491    6     Social Protection and Risk Management
1492   10                         Rural Development
1493   10                         Rural Development
1494   10                         Rural Development
1495    9                         Urban Development
1496    8                         Human Development
1497    5                     Trade and Integration
1498    4  Financial and Private Sector Development

[1499 rows x 2 columns]

In [72]:

#make new dataframe, replace all blank names using the dictionary from earlier#make new 

df = pd.read_json('data/world_bank_projects.json')

for x in range(len(df)) : 
    cell = df.iloc[x, 23]
    for part in cell: 
        if part['name'] == '' : 
            #print(codenames[str(part['code'])])
            part['name'] = codenames[str(part['code'])]

NameError: name 'codenames' is not defined

In [ ]:
#double check it's all good

print(df['mjtheme_namecode'].head(100))